// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMOuDUrUpJGTehdKogtrT0zCaVvevtpgU',
    appId: '1:470842902675:web:a92c4fcae67cf1ea01a566',
    messagingSenderId: '470842902675',
    projectId: 'ayucure-46cce',
    authDomain: 'ayucure-46cce.firebaseapp.com',
    storageBucket: 'ayucure-46cce.firebasestorage.app',
    measurementId: 'G-LHZXFL288S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhTWYca-UKGywoZg1veZlN5aNmfGWC0iA',
    appId: '1:470842902675:android:ecb9d24b84de7c7b01a566',
    messagingSenderId: '470842902675',
    projectId: 'ayucure-46cce',
    storageBucket: 'ayucure-46cce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAX_22j16PjFGenxb8aDSXxdlY_6OIO6c',
    appId: '1:470842902675:ios:bbaf59da0cb7322a01a566',
    messagingSenderId: '470842902675',
    projectId: 'ayucure-46cce',
    storageBucket: 'ayucure-46cce.firebasestorage.app',
    iosBundleId: 'com.example.ayucure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAX_22j16PjFGenxb8aDSXxdlY_6OIO6c',
    appId: '1:470842902675:ios:bbaf59da0cb7322a01a566',
    messagingSenderId: '470842902675',
    projectId: 'ayucure-46cce',
    storageBucket: 'ayucure-46cce.firebasestorage.app',
    iosBundleId: 'com.example.ayucure',
  );
}
